import Avatar from "@mui/material/Avatar";
import Card from "@mui/material/Card";
import Footer from "../components/footer";
import Head from "next/head";
import styles from "../styles/Home.module.css";

// Home component to render the landing page
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Profile Card Component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Card className={styles.card}>
          <div className={styles.cardUp}></div>
          <div className={styles.cardMiddle}>
            <h1 className={styles.name}>
              {" "}
              Victor Crest <span>26</span>{" "}
            </h1>

            <p>London</p>
          </div>
          <div className={styles.cardDown}>
            80K Followers 803K Likes 1.4K Photos
          </div>
          <Avatar
            className={styles.avatar}
            alt="User Photo"
            src="/image-victor.jpg"
            sx={{ width: 102, height: 102 }}
          />
        </Card>
      </main>
      <Footer />
    </div>
  );
}
